### ISSUE TITLE
/usr/bin/cpantorpm shows warning when run without command line arguments

### ISSUE THREAD

**Issue by mrdvt92** [SBECK-github/App-CPANtoRPM#10]
```
$ cpantorpm
Use of uninitialized value within @a in pattern match (m//) at /usr/share/perl5/vendor_perl/App/CPANtoRPM.pm line 477.
ERR:  No package given.
```

The uninitialized value should be trapped.  I would trap it with a test to see if there are no command line arguments then output a short syntax. (like `cpantorpm -h`)

**Comment by mrdvt92** [comment]
> if there are no command line arguments

This would fix my issue if you add at line 475:

```
$self->_usage, exit  unless @a;
```

**Comment by SBECK-github** [comment]
Sorry for the slow reply.  For some reason, I never received an email about this issue.  This will be fixed in the next release.
