### ISSUE TITLE
Override "Build pure_install"?

### ISSUE THREAD

**Issue by pjwelsh** [SBECK-github/App-CPANtoRPM#16]
There is a Perl module Text::VisualWidth::PP that uses Module::Build::Tiny as part of the "Build" file. Module::Build::Tiny does not support "pure_install" as an option. It does support "install", however.
Is there a cpantorpm way to fix this or will I need to patch?

According to the maintainer of both Module::Build::Tiny  Module::Build, pure_install and install are identical (maybe change to just "Build install"?).
https://www.reddit.com/r/perl/comments/n5so1r/was_there_ever_a_difference_between_pure_install/

**Comment by SBECK-github** [comment]
What version of cpantorpm are you using?  Since 1.09, support for Module::Build::Tiny is included and it should not have tried to run pure_install.

My guess is that you are using a very old version of cpantorpm (or perhaps a very old version of Module::Build::Tiny?).  Can you verify the versions of each?

**Comment by pjwelsh** [comment]
$ rpm -qf $(which cpantorpm)
perl-App-CPANtoRPM-1.14-1.el9.noarch

$ rpm -q perl-Module-Build-Tiny 
perl-Module-Build-Tiny-0.039-15.el9.noarch

Module::Build::Tiny rpm is from the OS and is not current.
However, I don't find "pure_install" in the latest metacpan version 0.047: https://metacpan.org/dist/Module-Build-Tiny/source/lib/Module/Build/Tiny.pm

**Comment by SBECK-github** [comment]
Newest version of cpantorpm, and although 0.039 is old, it's actually the same version I have on my OS as well.

When I did a simple build of Text::VisualWidth::PP, it worked for me.  So, can you run the same command you did before, but add the '-D' option and then provide me the full command AND the output from that command and I'll see if I can figure it out from that.

**Comment by pjwelsh** [comment]
Full command:
i="Text::VisualWidth::PP" ; cd ~/rpmbuild/ ; cpantorpm -D --install-type vendor $i 2>&1 |tee /tmp/$i.txt

[Text::VisualWidth::PP.txt](https://github.com/SBECK-github/App-CPANtoRPM/files/14376335/Text.VisualWidth.PP.txt)


Text::VisualWidth::PP.out attached

**Comment by pjwelsh** [comment]
Text::VisualWidth::PP.txt attached (not .out).

**Comment by SBECK-github** [comment]
There was a bug where the --install-type option was interfering with it detecting that it was using Module::Build::Tiny.  I've corrected the bug and uploaded a new version to CPAN.  You can get it there or here on github.

**Comment by pjwelsh** [comment]
Thank you for your help in this. Your efforts are much appreciated and useful!
