### ISSUE TITLE
Centos 7 lib patch 

### ISSUE THREAD

**Issue by twocolors** [SBECK-github/App-CPANtoRPM#7]
cpantorpm use 
`BASEDIR/lib/perl5/PERLVERS`
in Centos 7 default in perl
`/usr/lib64/perl5/vendor_perl` or `/usr/lib64/perl5`

**Comment by SBECK-github** [comment]
Sorry for the slow reply... I've been swamped here, but I'm trying to resolve a couple issues in cpantorpm and get a corrected release out this week.

Could you tell me what version of App-CPANtoRPM you are using, and how you observed this?  I've just built an RPM on Centos 7 and it worked fine, so I need a couple more details.

**Comment by SBECK-github** [comment]
Closing due to lack of information.
