### ISSUE TITLE
[request] %changelog from Changes

### ISSUE THREAD

**Issue by targzeta** [SBECK-github/App-CPANtoRPM#8]
Hi,
it would be nice to have the changelog section taken directly from the Changes file. What do you think about?

Thank you in advance,
Emanuele

**Comment by SBECK-github** [comment]
I would love to do this.  Unfortunately, the Changes files are very free form.  Having a reliable way to read them that will work across the majority of modules is not currently available.  There's only one module (Module-Metadata-Changes) and I've had problems getting it to work.  I'll continue to play with it, but for the time being, this isn't possible.
