### ISSUE TITLE
How to handle "Config command failed waiting on input" 

### ISSUE THREAD

**Issue by sreerajkksd** [SBECK-github/App-CPANtoRPM#9]
I tried to build a good number of perl packages to RPM using cpantorpm and it works totally fine.

I noticed an error "Config command failed waiting on input." common while building some packages like
Net::SSH::Perl, Spreadsheet::Read and Chart::Graph. Expected input is different for different packages, I couldn't find a documented approach to fix this. Is this something that I can fix using "--config" option ?

here is a simple reproducer:

`cpantorpm --debug -T vendor --clean-macros 'Net::SSH::Perl'`

**Comment by SBECK-github** [comment]
I just added the --config-input and --build-input options and was then able to make the Net::SSH::Perl module.  I added the options:

   --config-input 3 --config-input 'n'

to your command.  Give that a shot and let me know if that works.

**Comment by sreerajkksd** [comment]
Sorry for being late here. Where did you add this ? I couldn't find those options in the repository or in CPAN. Did you forget to push ?

**Comment by SBECK-github** [comment]
My apologies for omitting information.  The changes are in the SBECK-github branch.  I've also put a copy on my personal web site at:
   http://sullybeck.com/App-CPANtoRPM-1.10.tar.gz

**Comment by sreerajkksd** [comment]
Thanks, this works beautifully. Thanks for doing this.
I think, this is good to be merged and released to public consumption.

**Comment by sreerajkksd** [comment]
@SBECK-github Would you merge and release it when you get sometime ?

**Comment by SBECK-github** [comment]
It's pushed and released.

**Comment by sreerajkksd** [comment]
Thanks!
